###
POST http://{{HOST}}/api/auth/signin
Content-Type: application/json

{
  "username": "umit",
  "password": "123456"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
%}

###
POST http://{{HOST}}/api/auth/forgetpassword/umityild@gmail.com
Content-Type: application/json
Content-Language: TR

###
POST http://{{HOST}}/api/auth/forgetpasswordverify
Content-Type: application/json
Content-Language: TR

{
  "password": "123456",
  "maile": "umityild@gmail.com",
  "uuid": "456789"
}



###
GET http://{{HOST}}/api/1.0/product/products
Content-Type: application/json
Authorization: {{auth_token}}
Content-Language: TR

<> 2024-04-05T215444.401.json
<> 2024-04-05T215443.401.json
<> 2024-04-05T215007.401.json
<> 2024-04-05T214947.401.json
<> 2024-04-05T214757.401.json
<> 2024-04-05T214607.401.json
<> 2024-04-05T214435.401.json
<> 2024-04-05T214416.401.json
<> 2024-04-05T212413.500.json
<> 2024-04-05T212138.500.json

###
POST http://{{HOST}}/api/1.0/product/create
Content-Type: application/json
Authorization: {{auth_token}}
Content-Language: TR

{
  "productName": "Skye Clean Beyaz Kadın Sneake 1",
  "quantity": 20,
  "brand": "Puma"
}



###
POST http://localhost:8080/api/1.0/product/productutil/create
Content-Type: application/json
Authorization: {{auth_token}}
Content-Language: TR

{
  "price": 100,
  "status": false,
  "color": "#ffa500",
  "productId": 1,
  "quantity": 10,
  "size": "XL"
}



###
POST http://{{HOST}}/api/1.0/category/create
Content-Type: application/json
Authorization: {{auth_token}}
Content-Language: TR

{
  "catagoryName": "Test3",
  "description": "test3",
  "status": false
}


###
POST http://localhost:8080/api/1.0/product/productcategory/create
Content-Type: application/json
Authorization: {{auth_token}}
Content-Language: TR

{
  "categoryId":1,
  "productId": 1

}
